### ISSUE TITLE
Support for time elapsed

### ISSUE THREAD

**Issue by squaaawk** [arctic-hen7/forne#1]
A card should know how long has passed since the last review in order for some algorithms to intelligently schedule its weight. However, the only functionality rhai provides by default for dealing with times is through `timestamp`, which does not provide the absolute time and cannot be serialized for measuring the elapsed duration. I may be wrong, but I don't think there is currently a method to access the time elapsed since last review, and the rust side will have to manually provide additional information.

**Comment by arctic-hen7** [comment]
Ah, I wasn't aware Rhai wasn't capable of this! This should be pretty trivial to add, I'll do it this afternoon.

**Comment by arctic-hen7** [comment]
So much for that afternoon, but there is now a `get_seconds_since_epoch()` method exposed to Rhai that should work for you! @xorshift let me know if this is insufficient for your use-case and I'm happy to add some more helper functions.
